# Generated by Django 3.2.4 on 2021-07-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='logo',
            field=models.ImageField(default='media/nopicture.png', upload_to='customers'),
        ),
    ]
