# Generated by Django 3.2.4 on 2021-07-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='logo',
            field=models.ImageField(default='nopicture.png', upload_to='customers'),
        ),
    ]
