# Generated by Django 3.2.4 on 2021-06-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_task_task_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='description',
        ),
    ]
