# Generated by Django 3.2.4 on 2021-07-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_description_task_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created',
        ),
        migrations.AddField(
            model_name='task',
            name='lastmodified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
