# Generated by Django 3.2.4 on 2021-07-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
